# Generated by Django 2.0.6 on 2018-06-03 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('twitter_handles', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('description', models.TextField(max_length=500)),
                ('severity', models.IntegerField()),
                ('creation_date', models.DateField()),
                ('image', models.ImageField(default='Images/None/no-img.jpg', upload_to='Images/')),
                ('tweet_id', models.CharField(max_length=128, null=True)),
                ('status', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IssueMapApp.Department')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
